//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamingClient.FileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileService.FileServiceInterface")]
    public interface FileServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileServiceInterface/getStream", ReplyAction="http://tempuri.org/FileServiceInterface/getStreamResponse")]
        System.IO.Stream getStream(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileServiceInterface/getStream", ReplyAction="http://tempuri.org/FileServiceInterface/getStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> getStreamAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileServiceInterfaceChannel : StreamingClient.FileService.FileServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceInterfaceClient : System.ServiceModel.ClientBase<StreamingClient.FileService.FileServiceInterface>, StreamingClient.FileService.FileServiceInterface {
        
        public FileServiceInterfaceClient() {
        }
        
        public FileServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream getStream(string name) {
            return base.Channel.getStream(name);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> getStreamAsync(string name) {
            return base.Channel.getStreamAsync(name);
        }
    }
}
