//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Streams_Client.MainService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainService.MainServiceInterface")]
    public interface MainServiceInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MainServiceInterface/SyncFunction", ReplyAction="http://tempuri.org/MainServiceInterface/SyncFunctionResponse")]
        void SyncFunction(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MainServiceInterface/SyncFunction", ReplyAction="http://tempuri.org/MainServiceInterface/SyncFunctionResponse")]
        System.Threading.Tasks.Task SyncFunctionAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/MainServiceInterface/ASyncFunction")]
        void ASyncFunction(string data);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/MainServiceInterface/ASyncFunction")]
        System.Threading.Tasks.Task ASyncFunctionAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainServiceInterfaceChannel : WCF_Streams_Client.MainService.MainServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainServiceInterfaceClient : System.ServiceModel.ClientBase<WCF_Streams_Client.MainService.MainServiceInterface>, WCF_Streams_Client.MainService.MainServiceInterface {
        
        public MainServiceInterfaceClient() {
        }
        
        public MainServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SyncFunction(string data) {
            base.Channel.SyncFunction(data);
        }
        
        public System.Threading.Tasks.Task SyncFunctionAsync(string data) {
            return base.Channel.SyncFunctionAsync(data);
        }
        
        public void ASyncFunction(string data) {
            base.Channel.ASyncFunction(data);
        }
        
        public System.Threading.Tasks.Task ASyncFunctionAsync(string data) {
            return base.Channel.ASyncFunctionAsync(data);
        }
    }
}
